module.exports = class Data1730411238412 {
    name = 'Data1730411238412'

    async up(db) {
        await db.query(`CREATE TABLE "nft" ("id" character varying NOT NULL, "owner" text NOT NULL, "token_id" numeric NOT NULL, "token_uri" text NOT NULL, "type" text NOT NULL, "asset_contract" text NOT NULL, "metadata" jsonb NOT NULL, CONSTRAINT "PK_8f46897c58e23b0e7bf6c8e56b0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "new_listing" ("id" character varying NOT NULL, "listing_creator" text NOT NULL, "listing_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "price_per_token" numeric NOT NULL, "start_timestamp" numeric, "end_timestamp" numeric NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "reserved" boolean NOT NULL, "transaction_hash" text NOT NULL, "nft_id" character varying, CONSTRAINT "PK_b488e12815dbd3bf227ff7221b6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_52d2aee4957b27432a6c18b3ac" ON "new_listing" ("listing_creator") `)
        await db.query(`CREATE INDEX "IDX_afae6c5b3a1adc7580fab7497e" ON "new_listing" ("listing_id") `)
        await db.query(`CREATE INDEX "IDX_ff28595c60472a926ce04c4fcc" ON "new_listing" ("nft_id") `)
        await db.query(`CREATE TABLE "new_auction" ("id" character varying NOT NULL, "auction_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "minimum_bid_amount" numeric NOT NULL, "buyout_bid_amount" numeric NOT NULL, "time_buffer_in_seconds" numeric NOT NULL, "bid_buffer_bps" numeric NOT NULL, "start_timestamp" numeric NOT NULL, "end_timestamp" numeric NOT NULL, "auction_creator" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "transaction_hash" text NOT NULL, "nft_id" character varying, CONSTRAINT "PK_6b69f4ff181720f5ecd013e2e69" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_79bfdcf3a07f181152c9e246f0" ON "new_auction" ("auction_id") `)
        await db.query(`CREATE INDEX "IDX_6c7098939ad9d5fe2d153fb6a3" ON "new_auction" ("token_id") `)
        await db.query(`CREATE INDEX "IDX_3f0be436c8960700d9c1041b7b" ON "new_auction" ("nft_id") `)
        await db.query(`CREATE TABLE "new_sale_listing" ("id" character varying NOT NULL, "listing_creator" text NOT NULL, "listing_id" numeric NOT NULL, "asset_contract" text NOT NULL, "token_id" numeric NOT NULL, "buyer" text NOT NULL, "quantity_bought" numeric NOT NULL, "total_price_paid" numeric NOT NULL, "transaction_hash" text NOT NULL, "nft_id" character varying, CONSTRAINT "PK_18485428fcfb10fc2380f5e13b5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1d731a50584eba24e1beaae981" ON "new_sale_listing" ("listing_creator") `)
        await db.query(`CREATE INDEX "IDX_56579d70e6859b75fd3edca5be" ON "new_sale_listing" ("listing_id") `)
        await db.query(`CREATE INDEX "IDX_7b169e419df33050caecdae1d2" ON "new_sale_listing" ("asset_contract") `)
        await db.query(`CREATE INDEX "IDX_57997320e973151a329b81c6fa" ON "new_sale_listing" ("nft_id") `)
        await db.query(`CREATE TABLE "auction_closed" ("id" character varying NOT NULL, "auction_id" numeric NOT NULL, "asset_contract" text NOT NULL, "closer" text NOT NULL, "token_id" numeric NOT NULL, "auction_creator" text NOT NULL, "winning_bidder" text NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_b04a98ad26acc9309830bf11eec" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d2e1634168693b877c85218121" ON "auction_closed" ("auction_id") `)
        await db.query(`CREATE INDEX "IDX_a0c67476a82748dfa9f1f7feab" ON "auction_closed" ("asset_contract") `)
        await db.query(`CREATE INDEX "IDX_7bb0cfc2e72302638d8f9c611d" ON "auction_closed" ("closer") `)
        await db.query(`CREATE TABLE "all_listing" ("id" character varying NOT NULL, "listing_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "price_per_token" numeric NOT NULL, "start_timestamp" numeric NOT NULL, "end_timestamp" numeric NOT NULL, "listing_creator" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "reserved" boolean NOT NULL, "nft_id" character varying, CONSTRAINT "PK_614454c94a2f72e905ca1eb87fd" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5dc6adafda4963b8d9bf04eedf" ON "all_listing" ("nft_id") `)
        await db.query(`CREATE TABLE "new_bid" ("id" character varying NOT NULL, "auction_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "bidder" text NOT NULL, "bid_amount" numeric NOT NULL, "minimum_bid_amount" numeric NOT NULL, "buyout_bid_amount" numeric NOT NULL, "time_buffer_in_seconds" numeric NOT NULL, "bid_buffer_bps" numeric NOT NULL, "start_timestamp" numeric NOT NULL, "end_timestamp" numeric NOT NULL, "auction_creator" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "nft_id" character varying, CONSTRAINT "PK_82bbb4305e684aedf9b8e675d0a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9af0f648536999dcedd3dd7656" ON "new_bid" ("nft_id") `)
        await db.query(`CREATE TABLE "completed_listing" ("id" character varying NOT NULL, "listing_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "price_per_token" numeric NOT NULL, "start_timestamp" numeric NOT NULL, "end_timestamp" numeric NOT NULL, "listing_creator" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "reserved" boolean NOT NULL, "nft_id" character varying, CONSTRAINT "PK_16f6654e683fc0918ce55e230a1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d1a820577b352108d0522a02c1" ON "completed_listing" ("nft_id") `)
        await db.query(`CREATE TABLE "all_auction" ("id" character varying NOT NULL, "auction_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "minimum_bid_amount" numeric NOT NULL, "buyout_bid_amount" numeric NOT NULL, "time_buffer_in_seconds" numeric NOT NULL, "bid_buffer_bps" numeric NOT NULL, "start_timestamp" numeric NOT NULL, "end_timestamp" numeric NOT NULL, "auction_creator" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "winning_bid" jsonb NOT NULL, "is_auction_expired" boolean, "status" integer NOT NULL, "nft_id" character varying, CONSTRAINT "PK_ab94fecb5b40ddd8791d2e8c325" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a22797ea0c8f7382fbef4b3af9" ON "all_auction" ("nft_id") `)
        await db.query(`CREATE TABLE "completed_auction" ("id" character varying NOT NULL, "auction_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "minimum_bid_amount" numeric NOT NULL, "buyout_bid_amount" numeric NOT NULL, "time_buffer_in_seconds" numeric NOT NULL, "bid_buffer_bps" numeric NOT NULL, "start_timestamp" numeric NOT NULL, "end_timestamp" numeric NOT NULL, "auction_creator" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "winning_bid" jsonb NOT NULL, "is_auction_expired" boolean, "status" integer NOT NULL, "nft_id" character varying, CONSTRAINT "PK_eb0bb47198fc5c1cfe67dba148d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9b7ddc268fa5c4ca875e62cc0e" ON "completed_auction" ("nft_id") `)
        await db.query(`CREATE TABLE "all_offers" ("id" character varying NOT NULL, "offer_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "total_price" numeric NOT NULL, "expiration_timestamp" numeric NOT NULL, "offeror" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "nft_id" character varying, CONSTRAINT "PK_4e8c025b915d7e4f70fc33337fa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3d9ad319ed6142617aaefe5982" ON "all_offers" ("nft_id") `)
        await db.query(`CREATE TABLE "completed_offers" ("id" character varying NOT NULL, "offer_id" numeric NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "total_price" numeric NOT NULL, "expiration_timestamp" numeric NOT NULL, "offeror" text NOT NULL, "asset_contract" text NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "nft_id" character varying, CONSTRAINT "PK_b8920e680ea98fd520d33685a5a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5a7449e7aef2f3bdde5eef0f1e" ON "completed_offers" ("nft_id") `)
        await db.query(`CREATE TABLE "new_offer" ("id" character varying NOT NULL, "offeror" text NOT NULL, "offer_id" numeric NOT NULL, "asset_contract" text NOT NULL, "token_id" numeric NOT NULL, "quantity" numeric NOT NULL, "total_price" numeric NOT NULL, "expiration_timestamp" numeric NOT NULL, "currency" text NOT NULL, "token_type" integer NOT NULL, "status" integer NOT NULL, "transaction_hash" text NOT NULL, "nft_id" character varying, CONSTRAINT "PK_d5ec02a69099abe12cc997e6c7c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_451bbc388aee6d3db830beacee" ON "new_offer" ("nft_id") `)
        await db.query(`CREATE TABLE "accepted_offers" ("id" character varying NOT NULL, "offer_id" numeric NOT NULL, "asset_contract" text NOT NULL, "offeror" text NOT NULL, "quantity_bought" numeric NOT NULL, "seller" text NOT NULL, "token_id" numeric NOT NULL, "total_price_paid" numeric NOT NULL, "nft_id" character varying, CONSTRAINT "PK_8a052c171a00cba9015e0cdd05b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5e4a2f4727246ee7bd98f112b6" ON "accepted_offers" ("nft_id") `)
        await db.query(`ALTER TABLE "new_listing" ADD CONSTRAINT "FK_ff28595c60472a926ce04c4fccc" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "new_auction" ADD CONSTRAINT "FK_3f0be436c8960700d9c1041b7b1" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "new_sale_listing" ADD CONSTRAINT "FK_57997320e973151a329b81c6fae" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "all_listing" ADD CONSTRAINT "FK_5dc6adafda4963b8d9bf04eedfe" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "new_bid" ADD CONSTRAINT "FK_9af0f648536999dcedd3dd76560" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "completed_listing" ADD CONSTRAINT "FK_d1a820577b352108d0522a02c11" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "all_auction" ADD CONSTRAINT "FK_a22797ea0c8f7382fbef4b3af97" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "completed_auction" ADD CONSTRAINT "FK_9b7ddc268fa5c4ca875e62cc0e9" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "all_offers" ADD CONSTRAINT "FK_3d9ad319ed6142617aaefe5982b" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "completed_offers" ADD CONSTRAINT "FK_5a7449e7aef2f3bdde5eef0f1e8" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "new_offer" ADD CONSTRAINT "FK_451bbc388aee6d3db830beacee3" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "accepted_offers" ADD CONSTRAINT "FK_5e4a2f4727246ee7bd98f112b6b" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "nft"`)
        await db.query(`DROP TABLE "new_listing"`)
        await db.query(`DROP INDEX "public"."IDX_52d2aee4957b27432a6c18b3ac"`)
        await db.query(`DROP INDEX "public"."IDX_afae6c5b3a1adc7580fab7497e"`)
        await db.query(`DROP INDEX "public"."IDX_ff28595c60472a926ce04c4fcc"`)
        await db.query(`DROP TABLE "new_auction"`)
        await db.query(`DROP INDEX "public"."IDX_79bfdcf3a07f181152c9e246f0"`)
        await db.query(`DROP INDEX "public"."IDX_6c7098939ad9d5fe2d153fb6a3"`)
        await db.query(`DROP INDEX "public"."IDX_3f0be436c8960700d9c1041b7b"`)
        await db.query(`DROP TABLE "new_sale_listing"`)
        await db.query(`DROP INDEX "public"."IDX_1d731a50584eba24e1beaae981"`)
        await db.query(`DROP INDEX "public"."IDX_56579d70e6859b75fd3edca5be"`)
        await db.query(`DROP INDEX "public"."IDX_7b169e419df33050caecdae1d2"`)
        await db.query(`DROP INDEX "public"."IDX_57997320e973151a329b81c6fa"`)
        await db.query(`DROP TABLE "auction_closed"`)
        await db.query(`DROP INDEX "public"."IDX_d2e1634168693b877c85218121"`)
        await db.query(`DROP INDEX "public"."IDX_a0c67476a82748dfa9f1f7feab"`)
        await db.query(`DROP INDEX "public"."IDX_7bb0cfc2e72302638d8f9c611d"`)
        await db.query(`DROP TABLE "all_listing"`)
        await db.query(`DROP INDEX "public"."IDX_5dc6adafda4963b8d9bf04eedf"`)
        await db.query(`DROP TABLE "new_bid"`)
        await db.query(`DROP INDEX "public"."IDX_9af0f648536999dcedd3dd7656"`)
        await db.query(`DROP TABLE "completed_listing"`)
        await db.query(`DROP INDEX "public"."IDX_d1a820577b352108d0522a02c1"`)
        await db.query(`DROP TABLE "all_auction"`)
        await db.query(`DROP INDEX "public"."IDX_a22797ea0c8f7382fbef4b3af9"`)
        await db.query(`DROP TABLE "completed_auction"`)
        await db.query(`DROP INDEX "public"."IDX_9b7ddc268fa5c4ca875e62cc0e"`)
        await db.query(`DROP TABLE "all_offers"`)
        await db.query(`DROP INDEX "public"."IDX_3d9ad319ed6142617aaefe5982"`)
        await db.query(`DROP TABLE "completed_offers"`)
        await db.query(`DROP INDEX "public"."IDX_5a7449e7aef2f3bdde5eef0f1e"`)
        await db.query(`DROP TABLE "new_offer"`)
        await db.query(`DROP INDEX "public"."IDX_451bbc388aee6d3db830beacee"`)
        await db.query(`DROP TABLE "accepted_offers"`)
        await db.query(`DROP INDEX "public"."IDX_5e4a2f4727246ee7bd98f112b6"`)
        await db.query(`ALTER TABLE "new_listing" DROP CONSTRAINT "FK_ff28595c60472a926ce04c4fccc"`)
        await db.query(`ALTER TABLE "new_auction" DROP CONSTRAINT "FK_3f0be436c8960700d9c1041b7b1"`)
        await db.query(`ALTER TABLE "new_sale_listing" DROP CONSTRAINT "FK_57997320e973151a329b81c6fae"`)
        await db.query(`ALTER TABLE "all_listing" DROP CONSTRAINT "FK_5dc6adafda4963b8d9bf04eedfe"`)
        await db.query(`ALTER TABLE "new_bid" DROP CONSTRAINT "FK_9af0f648536999dcedd3dd76560"`)
        await db.query(`ALTER TABLE "completed_listing" DROP CONSTRAINT "FK_d1a820577b352108d0522a02c11"`)
        await db.query(`ALTER TABLE "all_auction" DROP CONSTRAINT "FK_a22797ea0c8f7382fbef4b3af97"`)
        await db.query(`ALTER TABLE "completed_auction" DROP CONSTRAINT "FK_9b7ddc268fa5c4ca875e62cc0e9"`)
        await db.query(`ALTER TABLE "all_offers" DROP CONSTRAINT "FK_3d9ad319ed6142617aaefe5982b"`)
        await db.query(`ALTER TABLE "completed_offers" DROP CONSTRAINT "FK_5a7449e7aef2f3bdde5eef0f1e8"`)
        await db.query(`ALTER TABLE "new_offer" DROP CONSTRAINT "FK_451bbc388aee6d3db830beacee3"`)
        await db.query(`ALTER TABLE "accepted_offers" DROP CONSTRAINT "FK_5e4a2f4727246ee7bd98f112b6b"`)
    }
}
